# XRPL TOML for Global Treasury
# Must follow XRPL Standard: https://xrpl.org/xrpl-toml.html

[METADATA]
network = "mainnet"

[[ACCOUNTS]]
address = "r4CGc6QvQEHFysd5GJJEEZFx24ys4S4rFw"
name = "Global Treasury"
website = "https://panorama2000.github.io/global-treasury/"
email = "panorama.2018@proton.me"

# ─── VND ────────────────────────────────────────────
[[CURRENCIES]]
code = "VND"
issuer = "r4CGc6QvQEHFysd5GJJEEZFx24ys4S4rFw"
name = "Vietnamese Dong"
desc = "Digital representation of the Vietnamese Dong (VND)"
icon = "https://raw.githubusercontent.com/panorama2000/global-treasury/main/flags/vnd.png"

# ─── IQD ────────────────────────────────────────────
[[CURRENCIES]]
code = "IQD"
issuer = "r4CGc6QvQEHFysd5GJJEEZFx24ys4S4rFw"
name = "Iraqi Dinar"
desc = "Digital representation of the Iraqi Dinar (IQD)"
icon = "https://raw.githubusercontent.com/panorama2000/global-treasury/main/flags/iqd.png"

# ─── IDR ────────────────────────────────────────────
[[CURRENCIES]]
code = "IDR"
issuer = "r4CGc6QvQEHFysd5GJJEEZFx24ys4S4rFw"
name = "Indonesian Rupiah"
desc = "Digital representation of the Indonesian Rupiah (IDR)"
icon = "https://raw.githubusercontent.com/panorama2000/global-treasury/main/flags/idr.png"

# ─── ARS ────────────────────────────────────────────
[[CURRENCIES]]
code = "ARS"
issuer = "r4CGc6QvQEHFysd5GJJEEZFx24ys4S4rFw"
name = "Argentine Peso"
desc = "Digital representation of the Argentine Peso (ARS)"
icon = "https://raw.githubusercontent.com/panorama2000/global-treasury/main/flags/ars.png"

# ─── IRR ────────────────────────────────────────────
[[CURRENCIES]]
code = "IRR"
issuer = "r4CGc6QvQEHFysd5GJJEEZFx24ys4S4rFw"
name = "Iranian Rial"
desc = "Digital representation of the Iranian Rial (IRR)"
icon = "https://raw.githubusercontent.com/panorama2000/global-treasury/main/flags/irr.png"

# ─── VEF ────────────────────────────────────────────
[[CURRENCIES]]
code = "VEF"
issuer = "r4CGc6QvQEHFysd5GJJEEZFx24ys4S4rFw"
name = "Venezuelan Bolívar Fuerte"
desc = "Digital representation of the Venezuelan Bolívar Fuerte (VEF)"
icon = "https://raw.githubusercontent.com/panorama2000/global-treasury/main/flags/vef.png"
